#[build]
#publish = "build/web"
#command = "./netlify_build.sh"
#
#[context.production.environment]
#PUB_CACHE = "/opt/build/cache/.pub-cache"

[[plugins]]
package = "netlify-plugin-flutter"
    [plugins.inputs]
    channel = "stable"

[build]
command = "flutter build web --release"
publish = "build/web"