// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUxyhvM54M2c_PMZQoIjvQgIAHUlil1No',
    appId: '1:802926305077:web:3af4d0279108386ebf367c',
    messagingSenderId: '802926305077',
    projectId: 'steamplayground-f24a7',
    authDomain: 'steamplayground-f24a7.firebaseapp.com',
    storageBucket: 'steamplayground-f24a7.firebasestorage.app',
    measurementId: 'G-SRCFBHY4LN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeu5SV3Cl0r0c0xy1iJmerBmMbxhaRj1Q',
    appId: '1:802926305077:android:9047e4c4741104e7bf367c',
    messagingSenderId: '802926305077',
    projectId: 'steamplayground-f24a7',
    storageBucket: 'steamplayground-f24a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5EvE_nvbIakylFn-5HqypsffgcZ4x-y0',
    appId: '1:802926305077:ios:ee18cc80b43a0794bf367c',
    messagingSenderId: '802926305077',
    projectId: 'steamplayground-f24a7',
    storageBucket: 'steamplayground-f24a7.firebasestorage.app',
    iosBundleId: 'com.cbpark.steamplayground',
  );
}
