name: Deploy Flutter Web App to GitHub Pages

on:
  push:
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4.1.1

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: 'stable'

      - name: Create .env file
        run: echo "FLUTTER_APP_API_KEY=${{ secrets.FLUTTER_APP_API_TOKEN }}" > assets/.env

      - name: Verify .env file creation
        run: |
          if [ -f assets/.env ]; then
            echo ".env file created successfully."
            # Mask the API key in the logs for security
            echo "::add-mask::$(cat assets/.env)"
            # Output the content of the .env file
            cat assets/.env
          else
            echo ".env file not found."
            exit 1
          fi

      - name: Copy .env file to build directory
        run: |
          mkdir -p build/web/assets
          cp assets/.env build/web/assets/.env

      - name: Verify .env file in build directory
        run: |
          if [ -f build/web/assets/.env ]; then
            echo ".env file successfully copied to build directory."
            # Mask the API key in the logs for security
            echo "::add-mask::$(cat build/web/assets/.env)"
            # Output the content of the .env file
            cat build/web/assets/.env
          else
            echo ".env file not found in build directory."
            exit 1
          fi

      - name: Install Dependencies
        run: flutter pub get

      - name: Import Flutter package
        run: flutter pub get

      - name: HREF
        run: flutter build web --base-href="/steamplayground/"

      - name: Build Flutter web
        run: flutter build web --release

      - name: Add .nojekyll
        run: echo > build/web/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: build/web
          publish_branch: gh-pages
