name: Deploy to Netlify

on:
  push:
  pull_request:

jobs:
  build:
    name: Build-action
    runs-on: ubuntu-22.04
    steps:
    # 1. 리포지토리 클론
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Flutter 설치
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    # 3. Flutter 웹 빌드
    - name: Build Flutter Web
      run: flutter build web --release

    # 4. Netlify에 배포
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2.0
      with:
        publish-dir: build/web
        production: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
